
services:
  postgres:
    image: postgres:16
    container_name: mini-marketplace-db
    environment:
      POSTGRES_DB: mini-marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/database.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./backend
    container_name: mini-marketplace-api
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: mini-marketplace
      DB_USER: postgres
      DB_PASSWORD: postgres
      PORT: 3000
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: mini-marketplace-frontend
    depends_on:
      - api
    ports:
      - "5173:5173"

volumes:
  pgdata:
